### ISSUE TITLE
Çoğ ayıp

### ISSUE THREAD

**Issue by tarikcayir** [ademilter/udemy-video-downloader#2]
Repoyu gizleyelim lütfen :P

**Comment by ademilter** [comment]
neden ayıp olsun hacıto. satın aldıgım videoyu indrmek için eklenti yazmayı düşündüm?
sen illegal yoldan düşündün galiba? satın almadığın videoya erişemezsin zaten.

**Comment by tarikcayir** [comment]
Yok be Hacıto, takılıyorum. GitHub'da öyle görünce yazayım istedim. Çok çalışmanın dezavantajları, maruz görünür lütfen :P :)
